### PR TITLE
Windows executable 2.4

### PR DESCRIPTION
**Pull request by WouterJD**
Please test and confirm that executables work, especially for iMagic because I cannot test.

@fritz-hh 
@vincentb2709

### CODE REVIEW

**Comment by fritz-hh** [comment]
```
>FortiusANT.exe
11:24:54,896: FortiusANT started
11:24:54,896: ------------------
11:24:55,435: Dongle - Using Dynastream Innovations dongle
Load firmware C:\Users\julie\AppData\Local\Temp\_MEI59602\../supportfiles/tacximagic_1902_firmware.hex for DEVICE ID 3561:1902 on Bus 000 Adresse 003
11:24:55,438: GetTrainer - Unable to initialise trainer
11:24:55,438: Tacx   - GetTrainer - Unable to initialise trainer
```

**Comment by fritz-hh** [comment]
As a side note: Instead of putting the exe files in the git repository, the usual way of delivering a software in github, is to make a [release](https://github.com/WouterJD/FortiusANT/releases), and upload the executables in the release. This is how nearly all github projects proceed (example: https://github.com/asciidoctor/asciidoctor/releases)
Usually this is where people expect the exe to be, when they visit a repository.

**Comment by WouterJD** [comment]
Cool, Will check

**Comment by WouterJD** [comment]
> Load firmware C:\Users\julie\AppData\Local\Temp\_MEI59602\../supportfiles/tacximagic_1902_firmware.hex for DEVICE ID 3561:1902 on Bus 000 Adresse 003
...
> I suspect that the exe does not find the firmaware file.
...
> need to be corrected to take into account the path to the firmware in the exe file
> I guess that the path needs to be set similarly to how its done in FortiusAntGui.py:
... 
implemented

**Comment by fritz-hh** [comment]
Download works now!
Thanks.

```
>"FortiusANT (1).exe"
19:06:26,615: Dongle - Using Dynastream Innovations dongle
Load firmware C:\Users\julie\AppData\Local\Temp\_MEI28442\tacximagic_1902_firmware.hex for DEVICE ID 3561:1902 on Bus 000 Adresse 003
....Stop CPU
....Start CPU
19:06:32,432: GetTrainer - iMagic head unit initialised
19:06:32,432: Tacx   - GetTrainer - iMagic head unit initialised
19:06:33,746: Ctrl-C to exit
19:06:33,766: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:34,769: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:35,774: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:36,779: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:37,783: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:38,783: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:39,800: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:41,041: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:42,043: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:43,047: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:44,049: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:45,052: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:46,054: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:47,058: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:48,062: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
19:06:49,065: Target=100W Speed= 0.1kmh hr=  0 Current= 14W Cad=  0 r= 128 100%
19:06:50,070: Target=100W Speed= 1.4kmh hr=  0 Current= 17W Cad=  0 r= 128 100%
19:06:51,074: Target=100W Speed= 4.3kmh hr=  0 Current= 40W Cad=  0 r= 226 100%
19:06:52,076: Target=100W Speed= 4.7kmh hr=  0 Current= 42W Cad=  0 r= 226 100%
19:06:53,078: Target=100W Speed= 4.5kmh hr=  0 Current= 41W Cad=  0 r= 226 100%
19:06:54,084: Target=100W Speed= 5.0kmh hr=  0 Current= 44W Cad=  0 r= 226 100%
19:06:55,085: Target=100W Speed= 3.6kmh hr=  0 Current= 36W Cad=  0 r= 226 100%
19:06:56,090: Target=100W Speed= 2.1kmh hr=  0 Current= 30W Cad=  0 r= 226 100%
19:06:57,093: Target=100W Speed= 0.4kmh hr=  0 Current= 14W Cad=  0 r= 128 100%
19:06:58,097: Target=100W Speed= 0.0kmh hr=  0 Current=  0W Cad=  0 r= 128 100%
```

**Pull request merged**
