### PR TITLE
Steering

### PR DESCRIPTION
**Pull request by marcoveeneman**
# Steering interface on BLE

This pull request adds initial support for steering in Zwift as described in #152.

Start FortiusANT with the `--steering` option on the command line. FortiusANT will advertise a steering characteristic which Zwift can connect to. When calibrating the rolling resistance, the steering interface is also calibrated, you get hints from the GUI. After you started pedalling, the GUI tells you to steer right, then middle.

Please review my changes and comment where needed.

### CODE REVIEW

**Comment by trygvelu** [comment]
Hi - nice to see that it is now possible to send steering data to zwift. Am I correct that extracting steering information from e.g. the blacktrack still needs to be implemented? Or is that already in the code somewhere?

**Comment by marcoveeneman** [comment]
Hi @trygvelu, yes you are correct. Currently the steering data is only fetched from the Tacx head unit itself. I see the blacktrack communicates over ANT+, so i think that can be added as a next step. I don't own a blacktrack personally, but i'm sure we can get this working as a community.

**Comment by switchabl** [comment]
I have a Blacktrack (came with my Genius). The ANT protocol for that is really simple, so I don't think it will take me long to implement. We will need to re-think calibration a bit though. The resistance calibration is only done for the Fortius while the Blacktrack can be used with any trainer. Actually the wired steering frame can be used with the Flow, too, and that doesn't have calibration (yet) either.

**Comment by trygvelu** [comment]
I have a blacktrack myself (also with Genius), but I'm not that familiar with the ANT profiles/protocol. I can assist with testing, if needed. Ideally I would think that steering could be implemented independent of the type of trainer hardware being used.

**Comment by WouterJD** [comment]
@switchabl 
> I don't think it will take me long to implement

I suppose implementation would be in line how head-units buttons from the Vortex are integrated.
We will have to mind the maximum number of ANT-channels, unfortunately they are not dynamically assigned (now)

**Comment by switchabl** [comment]
@WouterJD Yes, pretty much the same. There is a single page with the steering angle and we need to send a keep-alive every few seconds so it doesn't turn off.

As far as I know you can have channel numbers up to 255 as long as you don't enable more than 8 at the same time. I have never used that many before though.

**Comment by WouterJD** [comment]
Simple test to modify the channel numbers and see what happens

**Comment by wtal710174** [comment]
@marcoveeneman  Great work there! Thanks a lot for implementing the steering for Zwift. I did test the steering implementation today with my steering frame (not the Blacktrack obviously) on the Raspberry and it seems to work really well. I will keep testing an send you feedback in case I run into some bugs.
One thing I am thinking about is how to implement this in the headless Raspberry setups that some - including me - are using. I need to figure out how to read the stdout and use the information there to trigger a visual signal for the steering calibration. Would it be possible to store the information and calibrate the steering only if required? Looking at the source code it seems like this would require 2 variables to be stored somewhere. However not sure if the steering frame does send similar values every time.

**Comment by WouterJD** [comment]
@marcoveeneman sorry for the intermediate upgrade to 5.1 causing conflicts. Could you please look into that?

**Comment by kjoglum** [comment]
Is it a correct understanding that this PR will enable Zwift steering for my T1901/T1932/T1905 (steering frame) setup, i.e. Flow Multiplayer T2220 bundle? And it will communicate via the already established USB/FortiusANT interface?

**Comment by WouterJD** [comment]
Yes that is correct; it can be used with Zwift only - other CTP's do not support steering.
A final version has to be made and can then be integrated

**Comment by kjoglum** [comment]
As a follow up: Having a RPi 3b+ not being used, with some java/git experience (although totally unfamiliar with python), I have done an attempt to achieve my goal for testing the steering functionality for my T1901/T1932/T1905 setup against Zwift.

Making a fork of the latest @WouterJD branch, implementing and modifying the @marcoveeneman code for steering (both the "as is" code for CalibratedSupported trainers as well as trying to implement code for my trainer not CalibratedSupported).

So, apparently I have something going on, but not quite:
- I get both the trainer and steering functionality connected to Zwift, although shown as "No signal" (see picture below). Then running BLE setup RPi 3b+ FortiusANT / macOS Zwift (without BLE dongle), having the RPi < 50 cm from the mac. When starting training, no response from the avatar. Also tried via Zwift Companion app, but no response.

image

-  I also struggle with the calibration part within FortiusANT, which I do not seem to manage to trigger in a good way. Try to allow the start-up phase finish, and then initiating Steering Calibration for Cadence > 0 / Speed > 0. Although Cadence & Speed > 0, the calibration remains at the initialisation step.

For anyone interested, willing to comment/help, please have a look at my modified FortiusANT repository:
[https://github.com/kjoglum/FortiusANT](https://github.com/kjoglum/FortiusANT)

**Comment by kjoglum** [comment]
Yet another update on my behalf, having played around with the steering functionality of my T1901/T1932/T1905 setup. Now believe I have something working satisfactory, based on @marcoveeneman initial steering code, rebasing to latest @WouterJD branch, implementing steering calibration/functionality for non-calibration trainers. Please have a look and see if valid to implement:
[https://github.com/kjoglum/FortiusANT](https://github.com/kjoglum/FortiusANT)

As a note: The potmeter readings (at least for T1905) proves to be non-linear, so the updated code is introducing an additional calibration value for steering left (in addition to steering right and middle) to set steering angle in the range -45/45 degrees based on potmeter reading.

**Comment by frankhommers** [comment]
@switchabl What is the status on the Blacktrack VR implementation?

Would be awesome!

Maybe I can help or test?

**Comment by frankhommers** [comment]
@marcoveeneman it seems that @switchabl has disappeared from github since March.
Can we/I do something to get the Blacktrack VR steering working...?

**Comment by switchabl** [comment]
@frankhommers Sorry, life got in the way and this hasn't been much of a priority for me since I've been riding outdoors anyway. The protocol for the Blacktrack is here: https://gist.github.com/switchabl/75b2619e2e3381f49425479d59523ead (all the way at the bottom).

But I'm afraid Zwift has changed the steering protocol in order to lock out third-party implementations (https://www.dcrainmaker.com/2021/06/zwift-hardware-tidbits-breaking-steering-apple-tv-2021-updates-new-non-supported-trainers-list.html). So @marcoveeneman 's branch is probably broken right now. I think I've more or less managed to crack their new authentication mechanism. So I am cautiously optimistic that it can be done but more work needed.

There's also the chance that they will just break it again in a few months time. I'm not sure how keen I am on playing cat-and-mouse with them.

**Comment by frankhommers** [comment]
@switchabl ah yes, life is more important than a few lines of code ;-)

I have read DCRainmakers' blog post. And I understand your opinion about cat and mouse.

So I guess I am out of luck here... Maybe I'll just buy an Elite Sterzo Smart in order to be able to steer in a supported way.

**Comment by switchabl** [comment]
@frankhommers Maybe don't rush out to buy a Sterzo quite yet if you are not in a hurry. The good news is, it doesn't look like they have done a terribly good job locking us out. I think if all goes well I should have something working next weekend.

**Comment by frankhommers** [comment]
@switchabl Ah that would be awesome!! Can't wait to try!

**Comment by switchabl** [comment]
@frankhommers @marcoveeneman 
Quick update: I have indeed managed to figure out and implement their new authentication mechanism.
screenshot

I have also brought the steering up-to-date with master:
https://github.com/switchabl/FortiusANT/tree/steering

Blacktrack support still missing though. We also need to figure out how to do the calibration. This is currently botched onto the Fortius calibration which is not only messy but also means it doesn't even run if you're using another trainer. But all that is solvable. =)

**Comment by marcoveeneman** [comment]
Awesome! Looks like 'only' some small changes to the protocol were needed. Just wondering, how did you figure this out?

About the calibration part, i totally agree, it's not very nicely done currently. Back when i implemented the first version of steering i was thinking about adding a new steering member to te trainer class, which would implement a steering interface. This never happened and i went the quick&dirty way unfortunately.

It would be nice to setup some structure like this:
```python
class Steering
  ...
  def getAngle(raw_data):
    pass
  ...

class BlacktrackSteering(Steering):
  ...
  def getAngle(raw_data):
    <do blacktrack specific calculations here>
  ...

class FortiusSteering(Steering):
  ...
  def getAngle(raw_data):
    <do forties specific calculations here>
  ...
```

It's a while ago that i touched the FortiusANT codebase so i'm not sure where this would fit currently.

**Comment by frankhommers** [comment]
Yes we should make steering calibration "pluggable" in the startup sequence in some way. Maybe @WouterJD has some ideas about this?

**Comment by WouterJD** [comment]
Hi @frankhommers I'm fully confident that @switchabl will come with a good solution. Not having a steering unit, I cannot add much on testing.

**Comment by kjoglum** [comment]
Also being interested in the steering feature for my T1901/T1932/T1905 setup.

Have previously done some code modifications as well, [https://github.com/kjoglum/FortiusANT](https://github.com/kjoglum/FortiusANT), based on the following experience:
* Added code for retrieving/using both right, middle and left steering values from potmeter
* Added/revised code to be able to calibrate steering for trainer not being resistance-calibration supported

**Comment by switchabl** [comment]
@marcoveeneman I don't really want to give any hints to the Zwift/Elite people, so I'm not sure I should give too many details on the "how". The basic algorithm is still very much the same. The changes they made very narrowly address the weaknesses found in the original analysis:
1. The original version was only 16 bits, so it was possible to record and replay all possible combinations. The new one is 32 bits so this less feasible. It is however fundamentally weak and that doesn't get better with more bits.
2. The original version only authenticated the training app, not the steering device. So simulating a steering device didn't even need the authentication table. The new version consists of two challenge/response steps, so superficially it looks like it authenticates both. It turns out this is not really the case because the second one is not random so effectively only the steering device is authenticated now. If you just want to use an original Sterzo with your own software, you can now just replay a recorded exchange. Not sure if this is intentional or an oversight.

Also, yes, I will definitely go for a class hierarchy like that. I'm still figuring out the details though. Better get this (more or less) right the first time. Refactoring FortiusANT is always a bit scary.

@kjoglum Interesting. I'm curious what motivated the 3-point (piece-wise linear?) calibration? I was expecting a 2-point linear approach to work quite well because of the way the hardware works (raw value should be ``~(R_ref + R_pot)*C``). BUT, I can't really test that for properly for myself because I don't actually have a T1905 (I have a Blacktrack), I use this instead for testing...
t1905
 
Also, it turns out Zwift already has steering calibration built-in these days. That may or may not be good enough for our purposes. I will hopefully make some more progress on this (and Blacktrack) over the weekend.

**Comment by kjoglum** [comment]
@switchabl:
Due to irregular steering behaviour experienced with the 2-point approach, I ended up dismantling the steering frame to outrule any irregularities to the potmeter mount itself, followed by a 3-point approach to check actual output values for the potmeter, leading to including code for 3-point calibration. As shown below, the potmeter readings (at least for my T1905) are not 2-point linear.

The potmeter readings are varying a bit from time to time, but at an average I have `step = [(calib_middle - calib_right) / 45] = 5.0` for steering right and `step = [(calib_left - calib_middle) / 45] = 7.2` for steering left. Obviously, using 2-point calibration in my T1905 case would result in wrong angle values for left steering, in fact resulting in quite significant oversteering.

Skjermbilde 2021-11-11 kl  16 58 49

**Comment by switchabl** [comment]
@kjoglum Thank you, that is definitely helpful. And somewhat unfortunate. So I guess relying on Zwift calibration is probably a non-starter. It looks like they may be using an audio pot then. I did not see that coming. If that is the case, the 3-point piecewise approach is probably a good fit. I'd still want to make sure that it's not, like, the head unit doing something weird.

@marcoveeneman Did you observe this kind of behaviour too?

I will maybe try to get my hands on an actual T1905. And focus on the Blacktrack in the meantime. I think it uses an optical encoder instead, so should be

**Comment by marcoveeneman** [comment]
IIRC I used a 2 point calibration in this PR, same as the old Tacx Fortius software did: measure center, and measure most right. Based on those values calculate the raw value to angle factor. Middle is 0, most right is 45 degrees, left should be -45.

However, i remember that the values returned by the steering frame seemed to be affected by temperature. So after a while the values start drifting causing the calculation to be wrong. If you're training in a small room the temperature will definitely change, this might be a problem. Would be nice if someone could verify this. When i have some time i'll also check it.

**Comment by WouterJD** [comment]
Why would tacx conceptually build a steering unit that is different right/left, so I guess you try to compensate an individual issue.
Also - like previous improvements we made on the power curve - I would not try to make the software better than the (stability) of the hardware as Marco illustrates.
Even though mathematically challenging

**Comment by switchabl** [comment]
@WouterJD Yes, don't worry, I'm not quite ready to accept this either without further investigation. I still hope that this is in fact something that is weird/broken with the steering frame @kjoglum has (some alignment issue?).

From an engineering perspective using a potentiometer with a (non-linear) audio taper makes no sense of course. But it is possible that you could get those a lot cheaper somehow or the wrong ones got ordered or the linear one has a long lead time (very familiar problem right now). So you decide to use it anyway, at least for one batch, and fix it in software. It happens. More often than you might think.

If the old Fortius software used 2-point calibration that suggests this is not normal. But I think TTS4 actually does left-center-right calibration as well, so who knows.

In any case this is much simpler than the power curve issue. There are essentially just three possibilities:
1. we can let Zwift do the calibration (would be nice)
2. we need to do a 2-point calibration (right-center)
3. we need to do a 3-point calibration (left-right-center)
Neither is particularly interesting from a mathematical standpoint.

**Comment by kjoglum** [comment]
For sure, it could be some issues for my potmeter only, thus no need to make adjustments to the steering code, but wanted to point out the 3-point approach in case this would be the valid approach for similar setup as mine.

I have yet again dissassembled the steering frame to outrule any misalignment. And as @switchabl points out, for my Flow Multiplayer T2220 bundle (T1901/T1932/T1905) I have the **TTS 3.12 version** still running, indeed requiring left/middle/right steering calibration. And at least all measurements are consistent, whereas TTS shows converted values (compared to raw values from FortiusANT).

image

image

**Comment by switchabl** [comment]
Well, I now have the BlackTrack working and the left/center/right values don't exactly look symmetric either... Not quite sure why yet, but I guess 3-point calibration it is.

**Comment by WouterJD** [comment]
For what it's worth...readings from my Fortius, the self.Axis values are:

Position | self.axis | Delta | Sum
-- | -- | -- | --
all left | 1229 | 56 | 196
left | 1173 | 140 |
middle | 1033 |  |
right | 870 | 163 |
all right | 788 | 82 | 245

PS 1: the intermediate values (left and right) are an estimate and no exact position.

PS 2: Added in clsTaxNewUsbTrainer._ReceiveFromTrainer
```
print('Steering axis = ', self.Axis) # To investigate steering behaviour
```

**Comment by WouterJD** [comment]
Another thought on the subject.
Sorry that I did not check any steering-code yet, so the remark might be completely irrelevant.

Calibration is BLE-related, since the ANT-protocol does not support the steering.
This might suggest to do the calibration in the bluetooth-coding-area.

The calibration can also be done in the usbTrainer modules, where the USB-trainer is connected, of course only active when steering is used. This causes calibration to be done when hardware is connected and not when the bluetooth interface is opened.

Success with the developments.

**Comment by switchabl** [comment]
Thanks @kjoglum, @marcoveeneman and @WouterJD! I have now also confirmed that TTS4 uses the same approach (3-point piecewise-linear). So this is the way to go.

I now have a first preview (i.e. hopefully mostly works, but has very little real testing and is definitely not ready to merge) with BlackTrack support: https://github.com/switchabl/FortiusANT/tree/steering

* Steering is activated with "-S Blacktrack" (T2420/T2430) or "-S wired" (for T1905 with T1902/T1904/T1942/T1932) and requires working Bluetooth (+ ANT for BlackTrack)
* Option in settings dialog is still missing
* Calibration is "dynamic": the assumption is that on start-up the steering device is centered and that the highest/lowest values seen correspond to full left/right (or right/left for T1902 and Blacktrack). So you should steer full left and full right at some point before riding.

I am not totally convinced that this is a good idea. My worries are that 1) it may fail in some circumstances 2) it may be confusing to users (there should probably at least be a hint in the GUI). I have considered two alternatives that may still, but they would likely be a lot more work:
- on-demand interactive calibration: press a button to start calibration, ask user to steer left, press button, etc. Requires adding a button to GUI, maybe an additional text field as well. Not clear how this would work in the CLI/Raspberry Pi version.
- interactive calibration on start-up: Similar as before, but run on automatically on start-up, similar to trainer calibration. It may be possible to get away without additional UI elements. The problem is, it needs to run after the ANT loop is started (for the BlackTrack), but should probably not run at the same time as ANT-based trainer calibration (so either before or after). But I'm afraid making that happen probably needs major rework of the main loop and/or ANT-based trainer calibration.

Anyway, let me know what you think. I have a T1905 steering frame on the way, so I will probably do some more of my own testing and tweaking soon. I will also publish a pre-built Windows binary to make testing easier (not available yet).

**Comment by WouterJD** [comment]
@switchabl I was thinking also to make something like an initialization-period at the start but your dynamic behaviour is better. The recommendation is to do the calibration before starting the actual training.
Simple description: "At any time, steer far right / far left and FortiusAnt will assume that to be -45 or +45 degrees."; it might be usefull to give a console message when far left/far right calibration is set "Current position of steering is considered [+|-]45 degrees"

**Comment by WouterJD** [comment]
Command-line parameter -S was reserved for scs (speed and cadense sensor) but since that is not requested and unlikely to be implemented, I'm fine. It's the most obvious letter.

**Comment by switchabl** [comment]
@WouterJD Yes, that sounds good, I think. It will take some small changes to the calibration algorithm to be able to do that. But should not be too hard. Also probably add a message like "Steering device connected. Zeroing at current orientation."

It also should be relatively straightforward to just move those messages to a new steering status field in the GUI if we wish to do so at a later point.

**Comment by WouterJD** [comment]
I assume the USB trainer class will be enhanced with AxisLeft AxisMiddle AxisRight and Angle (in addition to Axis)
As soon as there's time, a visual steering image (picking up Angle) might be fun to make...

**Comment by frankhommers** [comment]
> Simple description: "At any time, steer far right / far left and FortiusAnt will assume that to be -45 or +45 degrees."; it might be usefull to give a console message when far left/far right calibration is set "Current position of steering is considered [+|-]45 degrees"

I am not sure if this is a good idea. If there is some interference or something which causes a value to spike, you'll have wrong steering for the whole session. I would opt for a separate step during the startup sequence.

**Comment by switchabl** [comment]
@WouterJD Not quite, the trainer class currently gets a `SteeringFrame` attribute that is derived from `clsSteeringUnit`. The steering unit class handles the calibration and gives you the calibrated steering angle (`Angle` property). The Blacktrack implementation derives from `clsSteeringUnit` too, so it is a drop-in replacement. The main loop does not care if which it is given. But the details may still change a bit.

@frankhommers Yes, this is one thing I am worried about, too. I use a median filter to pre-process the values. That should hopefully take care of spikes. If it doesn't work in practice, another alternative would be to use the first reasonably high/low value that is stable for ~1s for calibration. But if you mess it up, you would have to restart.

I also think that a separate step during start-up would be a clean solution. The problem is, I have thought about it long and hard and I'm not sure how to do it without completely restructuring `Tacx2DongleSub` function. And that is terrifying. `Tacx2DongleSub` is a 1000+ line behemoth. I am almost sure that I will break several unrelated things in subtle ways if I try.

[Eventually, `Tacx2DongleSub` should be rewritten. It should be split up into three loops, running in separate threads, for USB, ANT and BLE. And a lot of logic should be moved out to its own modules. That will solve several annoying problems and make everything more stable. It will also be a lot of work and need a lot of testing. If we wait for that, steering would be delayed for a long time.]

**Comment by WouterJD** [comment]
I admit that the main loop has grown from antifier into what it is now; knowing all interfaces and requirements from the start would certainly have led to a cleaner design. But as we all know, this happens and redoing is a lot of work AND requires a lot of testing, possibly with an extended period of issues.

The T1905 does not require too much intervention
- axis can be calculated into angle in the refresh() routine
- calibration can be done as discussed (implicit or with user-interaction, at startup only or on the fly)
- transmission of BLE is located in the bluetooth area
I would _think_ that this would not require too much rework in the code; and since I see three modules touched I gues I'm not far off track here.

@switchabl How does the blacktrack interface work? Is that an ANT-device to be paired and the interface to be translated to BLE?

**Comment by switchabl** [comment]
@WouterJD Yes, with the current (dynamic) calibration approach it is not a problem. The modifications to the main loop are minimal. Most of the steering code is in a separate module.

I have now improved the calibration routine somewhat. The calibration status is now shown on the console as suggested. Also, the new calibration is only applied if the axis value has been reasonably stable for a bit. It will need some more tweaks for sure.

Most importantly, there is now a binary package for Windows as well to facilitate testing. It bundles a version of Node.js (and dependencies) so can mostly ignore the usual instructions for BLE. Still, there are a couple of steps that may be required to run it:
1) Install the Visual C++ runtime (if it is not installed by already): https://aka.ms/vs/17/release/vc_redist.x86.exe
2) If you use a USB trainer, you still need the libusb driver: https://github.com/switchabl/t19xx_usb/releases/download/v1/libusb-win32_T19xx.exe
3) Replace the driver of your Bluetooth dongle with WinUSB using Zadig (https://zadig.akeo.ie/). See 3.8.3, step 4 in the handbook for more info.
4) Download and extract the binary package: https://github.com/switchabl/FortiusANT/suites/4512791178/artifacts/120594603
5) Run the included `FortiusANT.exe`

Also, this will not work on Windows 7 (because Node v14 does not), Windows 8.1 or higher is required.

To enable steering, select "wired" (for T1905) or "Blacktrack" in the settings (or use the `-S wired` or `-S Blacktrack` command-line options). You also need to enable Bluetooth (or add `-b`).

Known issues:
- Using the BlackTrack together with an ANT trainer seems to result in dropped bytes from the ANT dongle. I think I know why, but I will need to rework the ANT dongle code a bit to fix it.
- Calibration may not be as stable with pedal stroke analysis (-A) enabled (yet).

Let me know if you encounter any additional problems.

**Comment by frankhommers** [comment]
@switchabl Does this mean I can take that code and try it out?
I am aiming to run it on a Raspberry Pi btw.

**Comment by WouterJD** [comment]
Hi @switchabl I have read through the new code and it looks fine.

Would you be so kind to do two things:
- resolve the conflicts with the current FortiusAnt version; you are more in the code than I am, I would hate to brake the new steering code.
- add version comment at the top of the modified files; that's handy when comparing and having two files open.

Thanks, seem a solid piece of work.

As soon as done, I will add the -S to the json code and interactive settings; always a bit of a hassle to have three locations to define the settings, but that's what it is now :-)

**Comment by WouterJD** [comment]
PS. Regarding your last comment on the .exe for testing. There have been several questions "why did you not make an installer". The answer is the number of platforms and options, that alll have to be maintained. From that point of view I'm a bit carefull to integrate more, you already mentioned the remaining "prereqs" for it to work.
Perhaps the FA-link is the answer for those who do not manage too get the system work; the prepackaged rpi (see fortiusant,eu). The intention was to pick-up after the summer, but a series of things changed so that remained WIP.

**Comment by WouterJD** [comment]
> * Using the BlackTrack together with an ANT trainer seems to result in dropped bytes from the ANT dongle

I do not see anything specific in the code in steering.py, especially since the module only handles pages from its own channel.

**Comment by WouterJD** [comment]
> * Calibration may not be as stable with pedal stroke analysis (-A) enabled (yet).

Why would that be? Too much processing??

**Comment by switchabl** [comment]
@frankhommers Yes, it has been mostly working for a while. You may still have some problems with the Blacktrack (because of the ANT packet drops), I am not sure how bad it is in practice. Not sure about setting everything up on the Raspberry Pi but I guess you already have the normal version of FortiusANT running anyway?

@WouterJD Thanks for taking a look. I still need to fix a few things, so it is not quite ready anyway. But the overall structure is unlikely to change now. I admit I never look at the version comments (I find using git to compare and check changes much easier) but I will add them when I am done and then create a clean pull request.

The binary package is basically the best thing I could make *without* making an installer. Think of it as the Windows exe but with all the Bluetooth stuff already included. So the prerequisites are more or less the same as with the normal exe. But it is not meant to be merged into master. It is just a way to let people easily test experimental versions without installing multiple GB of Node.js-related things.

But you are right, I was thinking about an installer. An installer would get rid of all the prerequisites (except for the WinUSB-driver for BLE, unfortunately). And the work I have already done on the binary package should be quite helpful. More still to be done though.

I have seen the FA-Link. In general, I think selling hardware appliances is very much a legitimate way to monetize open-source projects. I would probably be somewhat worried about it becoming a support nightmare (how to debug problems? how to deploy updates/bug-fixes? and so on). But you have probably thought about this a lot more than I have. I do see the appeal of a plug-and-play solution. I had considered designing a replacement head-units with ANT/BLE built-in at one point (not based on FortiusANT, custom hardware and firmware). Of course that is a much more ambitious project and in the end I concluded that it would probably not be economically viable.

**Comment by switchabl** [comment]
> I do not see anything specific in the code in steering.py, especially since the module only handles pages from its own channel.

I think the ANT code gets overwhelmed with too many packets (the dongle itself can handle it fine, it is just the implementation). So the problem is not with the steering code directly, rather it exposes problems with the ANT dongle code. I have had a closer look and there are actually multiple issues that can potentially result in dropping data:
1) The read buffer size is 1000 bytes which is not a multiple of the endpoint packet size (64 bytes). Most other implementations I have seen use 4096 bytes to be on the safe side.
2) The dongle is only read every 0.25s. If you have a lot of traffic, a large number of messages can accumulate in that time and overflow the dongle buffer.
3) Reads are done with (short) time-outs. Unfortunately, time-outs work by 1) initiating a transfer and 2) cancelling it if it times out. But there is no guarantee that cancellation succeeds and if any data still comes in after the time-out, it is lost.
4) If a frame is split between multiple buffers (there is no guarantee that this can't happen), it is currently just dropped.

1) is trivial. 2), 3) and 4) can all be fixed by having a thread running in the background, reading into a buffer. And then just having Read take bytes from that buffer. It is what everyone else does. I'll take a stab at it this weekend.

I suspect that 2) may explain some of the CYCPLUS problems as well, if the CYCPLUS has a smaller buffer and doesn't handle overflow.

> Why would that be? Too much processing??

The calibration routine looks at the last 5 values. Usually that is about 1.25s but with -A it is much shorter, so calibration may be updated even if the angle is not stable. I still need to implement a dynamic window length.

**Comment by WouterJD** [comment]
> a support nightmare

Well practice shows it's plug-and-play and no worries after.
Sometimes some installation guidance, but that's part of the deal.
Since the rpi is dedicated, no problems, I'm sure achieving this on windows would cause far more headache.

**Comment by WouterJD** [comment]
I hope following observations help

> 2. The dongle is only read every 0.25s

This is not necessarily true; FortiusAnt data is transmitted every QuarterSecond, the ANTdongle is read every cycle of the main loop. The main loop runs at 0.02s or 0.25s interval, depending on the PedalStrokeAnalysis.

I think I have not seen the 1000bytes being filled. If more data than 900 bytes is received a message is given, which I never see happening. Also when incomplete messages are received, a warning is printed on the console, something I do not see either.

In the comment on "def __ReadAndRetry(self, timeout):" I see I have been studing the subject resulting in the current settings. I doubt a separate thread (with the required overhead) would help.

Regarding the program's architecture; the loop has evolved from antifiers loop, which was single threaded. John/antifier would certainly recognize the setup, even though it has changed a lot. Creating FortiusAnt caused me to learn ANT and python, perhaps with today's knowledge I would build differently. But hey, isn't that always the case.

Since the code works on the systems and platforms we support, I would be shy to redesign.

>But the overall structure is unlikely to change now.

I would certainly agree to that.

**Comment by WouterJD** [comment]
I hope following observations help

> 2. The dongle is only read every 0.25s

This is not necessarily true; FortiusAnt data is transmitted every QuarterSecond, the ANTdongle is read every cycle of the main loop. The main loop runs at 0.02s or 0.25s interval, depending on the PedalStrokeAnalysis.

I think I have not seen the 1000bytes being filled. If more data than 900 bytes is received a message is given, which I never see happening. Also when incomplete messages are received, a warning is printed on the console, something I do not see either.

In the comment on "def __ReadAndRetry(self, timeout):" I see I have been studing the subject resulting in the current settings. I doubt a separate thread (with the required overhead) would help.

Regarding the program's architecture; the loop has evolved from antifiers loop, which was single threaded. John/antifier would certainly recognize the setup, even though it has changed a lot. Creating FortiusAnt caused me to learn ANT and python, perhaps with today's knowledge I would build differently. But hey, isn't that always the case.

Since the code works on the systems and platforms we support, I would be shy to redesign.

>But the overall structure is unlikely to change now.

I would certainly agree to that.

**Comment by WouterJD** [comment]
> the Blacktrack (because of the ANT packet drops)

Perhaps this is the key thing; how many packets does the Blacktrack send? It should NOT cause a big stream of packets, as far as I understand ANT, from the nature of the protocol.

**Comment by switchabl** [comment]
@WouterJD The Blacktrack natively sends 16Hz which made it completely unusable. I have actually reduced the channel to 4Hz already, so it only receives every 4th message. Now I only have occasional drops if an ANT trainer is used at the same time. Without an ANT trainer the Blacktrack works fine. So it is a question of traffic. (This is all with a Garmin ANTUSB-m.)

I am aware that the main loop can run faster (with pedal stroke analysis) but I believe the ANT dongle is still only read every 0.25s. That is only part of the problem though. I have seen your comments about the time-out and that you have found 20ms to work. On your PC it might even work with a Vortex and Blacktrack (or not). On mine it doesn't. The point is that there is no guarantee. There may be a Windows Update tomorrow that breaks it for you. The libusb-win32 documentation states:
> Since Windows (same for Linux and Mac OS X) is not an RTOS, it is not a good idea to use small timeout value like 10ms or 100ms.

As a solution they suggest:

> 1) Use the async transfer functions and usb_reap_async_nocancel()
> 2) Use the sync transfer functions from within their own thread and always use INFINITE for the timeout.

Option 1 is not available in Python. Option 2 is what I usually see in other software that uses libusb.

I am very confident an extra thread would resolve the problem and improve overall stability. I don't see a good alternative either. And it is not as bad as you might think. There will be no change to the main loop and the overall architecture, only antDongle.py.

The read buffer size: yes, I have only seen the "too much data" error 2-3 times ever. But it is easy to change, so might as well do it right now. If you run the debug version of libusb-win32, it actually produces a warning message about this on every read.

I understand why FortiusANT is the way it is and I can relate (I also admit is is sometimes frustrating). I believe it is not just a question of experience, it also grew a lot bigger than was originally intended. That sort of thing happens a lot. As a rule, I try to improve things I need to change anyway but not make unnecessary breaking changes elsewhere.

I am happy to hear that the FAlink is working out for you. My ultimate goal *is* to make the Windows version almost as easy to use. But that is in the future.

**Comment by WouterJD** [comment]
@switchabl thanks for detailed response. You may probably be right, there should be a thread that's permanently be available to receive data from ANT.

FortiusAnt is now headunit-centric, with main loop to read data from the head unit. Even when there is no head unit. The ANTloop is active only when the Fortius calibration is completed.

Adding an ANT thread would be correct for the ANTdevice, but actually a bigger redesign of the main loop would be required.
Devices should be paired properly like Zwift and others do.

Happy to read your ideas on the subject, perhaps finalize steering first (knowing the loop could be improved) so we have a stable baseline and the concentrate on the ANTloop only in a next step. I would recommend not to do it in this update, which is open for 10 months now

**Comment by WouterJD** [comment]
> use INFINITE for the timeout

Of course ANT-handing improvement remains on my mind.
If the read has an infinit timeout, how do you send data? (Assuming that the ANTdongle does not necessarily produce data at regular intervals ending the read)

How would the ANT-loop look like, if not as below?

```
While True
  read from ANT (timeout = 20ms or INFINIT)
  make data available

  if data is to be sent; send to ANT
  ## Note that this only happens after timeout OR data is provided

  wait short time
```

**Comment by WouterJD** [comment]
Hi @switchabl how are steering things going?

**Comment by WouterJD** [comment]
Hi @switchabl do you plan finalizing steering? Can I assist here? Would be a nice Xmas present to release it.

**Comment by switchabl** [comment]
@WouterJD Sorry, busy week. Blacktrack support will be half-broken until #341 is fixed. I hope everything can be sorted out before Christmas (and will try to do some more test rides in the meantime). If it is not, I would rather delay a bit than ship out something that doesn't work properly.

**Comment by WouterJD** [comment]
Agree, no rush. Thanks for the hard work and stay healthy👍

**Comment by frankhommers** [comment]
Hi @switchabl, can we do something to get this stuff merged? I am kind of lost now ;-)

**Comment by WouterJD** [comment]
@frankhommers does the branch from @switchabl work?

**Comment by frankhommers** [comment]
I haven't tried yet. If I do, will that speed things up?

**Comment by WouterJD** [comment]
It sure would; knowing that the steering device works for you is always an advantage.
The FortiusAnt work is more like a winter-time job; but I can give it a try

**Comment by frankhommers** [comment]
I have merged switchabl's branch into your master branch.
I do see Blacktrack options, but I don't see anything happening... Yet

**Comment by WouterJD** [comment]
Perhaps it's not the github correct way of working, and appologies for that if so.
@marcoveeneman has created steering
@switchabl has implemented blacktrack
All that precious work is now merged into branch **steering**

Therefore this PR is closed, I will create a new PR for the steering branch.

Guys thanks for the work and support!

**Pull request closed without merging**
