### PR TITLE
Add license

### LINKED ISSUE #167: FortiusANT license?
I just realized that there is no mention anywhere how FortiusANT is licensed. Now, from what I gather you consider this open source and are fine with other people making their own versions. And I don't anticipate anyone sueing anyone. But it does leave everyone sharing it and modifying it on somehwat shaky ground and it should be easy to fix.

1) Decide on a license. Probably the most popular options:
- MIT license: do what you want
https://opensource.org/licenses/MIT
- BSD license: do what you want, but you must credit the original author(s) in the software and the documentation
https://opensource.org/licenses/BSD-2-Clause
- GPL license: you can share and modify it, but if you do you have to share the source code as well
https://opensource.org/licenses/GPL-3.0
2) Ask everyone who contributed (non-trivial) code if they are ok with it
3) Add LICENSE file to Github with the license text

Because of step 2) it should maybe be done sooner rather than later, because it becomes more work as more people contribute.

### PR DESCRIPTION
**Pull request by marcoveeneman**
This PR applies the GPLv3 license to FortiusANT, as discussed with @WouterJD.

Following GitHub-users have contributed to the existing code; please approve this PR ASAP to agree with the license change:
- @mattipee 
- @fritz-hh
- @cyclingflow
- @switchabl

Fixes #167

### CODE REVIEW

**Review by WouterJD — APPROVED** [review]

**Review by switchabl — APPROVED** [review]

**Comment by mattipee** [comment]
@marcoveeneman  Where do I approve? Do you need to add me as a reviewer?

**Comment by switchabl** [comment]
@mattipee Files changed -> Review changes
But just saying you approve will be fine too I'm sure ;-)

**Review by mattipee — APPROVED** [review]

**Comment by marcoveeneman** [comment]
We still need approval from @fritz-hh and @cyclingflow

**Comment by fritz-hh** [comment]
OK for me!

**Comment by cyclingflow** [comment]
sorry for the delay
i approve

**Pull request merged**
