### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by decodeais**
I hope this is the right way to show you this little problem in the comment. Git is so new and confusing for me, please tell me if I make something wrong.

### CODE REVIEW

**Comment by WouterJD** [comment]
Hi @decodeais could you please explain the intention of this pull request, because you offer 26 files to be changed, including the executable.

It seems as if you offer to merge Raspberry_Release6 branch into master, I will do that when some testing has been done

**Comment by decodeais** [comment]
It was something strange, I  think I did something wrong. I made only
changes in  the  comment for the IO's in raspberry.py . I think I
pressed a wrong key somewere, sorry.<div
id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virenfrei. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2021-03-05 22:04 GMT+01:00, Wouter Dubbeldam <notifications@github.com>:

**Comment by decodeais** [comment]
I'm new to git and pressed a wrong key. I changed a comment for the IO's.

**Comment by decodeais** [comment]
Please delete this mistake.

**Pull request closed without merging**
