### PR TITLE
Strava badge

### PR DESCRIPTION
**Pull request by marcoveeneman**
### This PR adds a badge to the readme file indicating the member count of the FortiusANT Strava club.

I don't know if you want to integrate this, but i thought it would be a funny add-on :) 

[Custom badge](https://www.strava.com/clubs/804672)

---

The badge data is fetched from a rest endpoint of a small python application (using Flask) that runs on Heroku. The application responds with json data to the /strava endpoint, such that Shields.io can use it to generate the badge. The member count is fetched from Strava using the stravalib python library and cached for five minutes in order to not reach the rate-limit on the Strava API.

Currently the application runs on my own Heroku account. If needed i can help setting this up for a different account.

---

http://shields.io/endpoint
http://developers.strava.com/docs/reference/#api-Clubs-getClubById
https://devcenter.heroku.com/articles/python-support
https://github.com/hozn/stravalib
https://flask-restful.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by WouterJD** [comment]
Nice gadget; the image displayed might be larger / attracting attention.
We know it's there and therefore see it - most users will not even see it.

If you like, make it "more visible"

**Comment by marcoveeneman** [comment]
> Nice gadget; the image displayed might be larger / attracting attention.
> We know it's there and therefore see it - most users will not even see it.
> 
> If you like, make it "more visible"

This is not really how badges work. It is a predefined format in which you can show some data. The colouring should attract users to look at it. It is not uncommon for a project to show a variety of badges on the readme page.

I could change the badge to the following format, which is the largest:
[Custom badge](https://www.strava.com/clubs/804672)

All options are listed here:
1. [Custom badge](https://www.strava.com/clubs/804672)
2. [Custom badge](https://www.strava.com/clubs/804672)
3. [Custom badge](https://www.strava.com/clubs/804672)
4. [Custom badge](https://www.strava.com/clubs/804672)
5. [Custom badge](https://www.strava.com/clubs/804672)

**Comment by WouterJD** [comment]
Helder; nu nog wat commentaar en uitleg.
En dan publishen :-)

**Review by simonperneel — APPROVED** [review]

**Review by simonperneel — APPROVED** [review]

**Comment by marcoveeneman** [comment]
@WouterJD I had some spare time and added a few comments and documentation about the strava badge.

**Comment by WouterJD** [comment]
Nice gadget!

**Pull request merged**
