### PR TITLE
Add gitattributes and fix line endings

### PR DESCRIPTION
**Pull request by marcoveeneman**
Line endings were not automatically handled by git yet, causing files in the repository to not have consistent line endings. This can cause annoying problems with pull requests. By adding the .gitattributes file to the repository this problem will be solved since all clients will now treat line endings the same way.

See https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings for more information regarding .gitattributes.

### CODE REVIEW

**Comment by WouterJD** [comment]
Marco

I have investigated this and discussed with you already some time ago.
We know that there are open branches outside, so I have tried to write down a working-instruction how to handle that

https://github.com/WouterJD/FortiusANT/wiki/FortiusANT-development-guidelines#new-lines

Please check whether that is correct.

My idea is:
- Treat master as described, then master is done (I assume this PR is running behind, with exception of .gitattributes)
- From that moment, no branches can be merged if they do not have the .gitattributes defined
- I will have to handle my #103 branch as described
- Same for you for your working-branches, as well as e.g. @switchabl, I will send him a separate note

Perhaps would be good to have @switchable and @cyclingflow approve this PR

Is that the way to go to avoid issues?



Also, would it be "safer" to exclude all files that we definitely want untouched:

```
# See https://git-scm.com/docs/gitattributes

# https://git-scm.com/docs/gitattributes#_text

*       text=auto
*.txt   text

# Declare files that will always have CRLF line endings on checkout.
# https://git-scm.com/docs/gitattributes#_eol
*.bat   text eol=crlf

# Declare files that must be untouched
*.hex   -text
*.ico   -text
*.jpg   -text
*.pdf   -text
*.xls*  -text
```

**Comment by marcoveeneman** [comment]
@WouterJD i read the page and it looks good to me. Just one remark: When a branch does _not_ have the .gitattributes yet, but master does, the branch must *not* commit it. This way, you get the line endings up-to-date and prevent a merge conflict on the .gitattributes file.

Indeed this branch is outdated, i'll update it to master.

**Comment by marcoveeneman** [comment]
Branch should be up to date with master now. I included your suggestion regarding binary files, however i replaced `-text` by `binary`, which is the preferred way to indicate a binary file.

**Comment by marcoveeneman** [comment]
> Marco
> 
> I have investigated this and discussed with you already some time ago.
> We know that there are open branches outside, so I have tried to write down a working-instruction how to handle that
> 
> https://github.com/WouterJD/FortiusANT/wiki/FortiusANT-development-guidelines#new-lines
> 
> Please check whether that is correct.
> 
> My idea is:
> 
> * Treat master as described, then master is done (I assume this PR is running behind, with exception of .gitattributes)
> * From that moment, no branches can be merged if they do not have the .gitattributes defined
> * I will have to handle my #103 branch as described
> * Same for you for your working-branches, as well as e.g. @switchabl, I will send him a separate note
> 
> Perhaps would be good to have @SwitchaBLE and @cyclingflow approve this PR
> 
> Is that the way to go to avoid issues?
> 
> Also, would it be "safer" to exclude all files that we definitely want untouched:
> 
> ```
> # See https://git-scm.com/docs/gitattributes
> 
> # https://git-scm.com/docs/gitattributes#_text
> 
> *       text=auto
> *.txt   text
> 
> # Declare files that will always have CRLF line endings on checkout.
> # https://git-scm.com/docs/gitattributes#_eol
> *.bat   text eol=crlf
> 
> # Declare files that must be untouched
> *.hex   -text
> *.ico   -text
> *.jpg   -text
> *.pdf   -text
> *.xls*  -text
> ```

Regarding the wiki page, did you also have a look at this? https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by switchabl** [comment]
Fixing the line breaks seems like a good idea to me. Now that master branch is fixed, I will fix my development branches as well.

**Pull request merged**
