### PR TITLE
Retry reset and read Ant dongle

### PR DESCRIPTION
**Pull request by martin-vi**
Observed with a Dynastream Innovations ANTUSB2 adapter, FortiusAnt no longer starts. The error: No expected reply from dongle. So far only physical reconnect helped.

During debugging it became clear that only after a new reset the desired reset msg can be read.

See also https://github.com/WouterJD/FortiusANT/issues/137

### CODE REVIEW

**Comment by WouterJD** [comment]
@martin-vi thanks for this extension to FortiusANT

I have following questions
- Why did you create the _resetDongle() function instead of putting the commands in the "for _ in range(2):" retry loop. If I understand correctly, the function is not used elsewhere.
- Do you have an explanation why the reset must be sent twice? Is the 0.500 second wait too short?
- What does the dongle return the first time? Nothing or something unrecognized.

**Comment by WouterJD** [comment]
I have implemented the retry, but without splitting code using the sub-function.
Thanks for the improvement

**Comment by martin-vi** [comment]
@WouterJD thanks for your effort. Sorry that I was not able to answer promptly. About the questions:

> Why did you create the _resetDongle() function instead of putting the commands in the "for _ in range(2):" retry loop. If I understand correctly, the function is not used elsewhere.

The local function has no deeper purpose. Occasionally I try to improve the readability with local functions. 

> Do you have an explanation why the reset must be sent twice? Is the 0.500 second wait too short?

No I have no explanation for this. The phenomenon occurs erratically. If it occurs blocked it needs the retry. Even a new ForticusAnt (without retry) will not help. Therefore I am very grateful that the fix was implemented.

> What does the dongle return the first time? Nothing or something unrecognized.

While debugging I could see that the dongle received data. But nothing that fulfilled the condition:
https://github.com/WouterJD/FortiusANT/blob/6ff4e71e84b14a2090d76c8ad543f3152424d30e/pythoncode/antDongle.py#L380

If desired I can try to get to the bottom of the problem and provide debug logs.

**Comment by WouterJD** [comment]
> If desired I can try to get to the bottom of the problem and provide debug logs.

Would be good; if the response is recognizable we could handle the content.

**Pull request closed without merging**
