### PR TITLE
Status.LED's for headless use of RaspberryPi

### PR DESCRIPTION
**Pull request by decodeais**
This function is enabled by commandline option -L
LED IO-port 25 shows USB-Tacx connected
LED IO-port 25 toggle shows Data transfer
LED IO-port 24 shows cadence present, to check the pacement of Reed-Contact and Magnet
LED IO-port 23 show ANT+ Dongle connected

### CODE REVIEW

**Comment by WouterJD** [comment]
Please check how comment is organized in the original code and adde comment accordingly

**Comment by switchabl** [comment]
@decodeais The Visual Studio project files (.vs directory) should probably be removed as well before this is merged.

**Comment by WouterJD** [comment]
I'll pick it asap.

**Comment by WouterJD** [comment]
By the way; what raspberry do you use.
I consider buying obe, please recommend

**Comment by switchabl** [comment]
@WouterJD There is probably no reason not to get a Pi 4B (unless you can find a 3B+ at a very good price). The one with 4GB RAM is more than enough, even 2GB is plenty for most things. 8GB is really only for things like running lots of containers or VMs.

You may want to pick up a Pi Zero W too if you can get one at a reasonable prize (~10€). That is probably the most attractive one for a stand-alone FortiusANT board. But it is less easy to use and much slower, so it is not really a replacement for the "big" one for general purposes (and learning).

**Comment by WouterJD** [comment]
Thanks!

**Comment by WouterJD** [comment]
I am spoiled by quite good laptops, 
a startekit pi4 8gb would be overkill for the purpose but most future proof and allowing for all kinds of experimenting

**Comment by WouterJD** [comment]
This is what I find as starterkit in NL...
https://www.sossolutions.nl/raspberry-pi-4-model-b-8gb-starter-kit-compleet

**Comment by decodeais** [comment]
Hello please take a Fast 16GB SD-Card
You need it for compiling th wxPython Wheel !!!

**Comment by decodeais** [comment]
With the Raspi4 it took 4h to compile the wheel. If you have done it, you can put  the SD-Card into a cheaper Raspi.

**Comment by switchabl** [comment]
There is nothing wrong with the 8GB of course, except that it is quite expensive. To me the 4GB is the future-proof one and the 8GB is for special applications. Keep in mind: this is not a PC, it is probably too slow for most things that you would do with 8GB on a PC. But nothing wrong with getting nice things because you can! For the price of the 8GB, there is also the Pi 400 which is basically the 4GB one built into a keyboard with a slightly faster processor (it is a bit like the old PCs from the 80s!). If you plan to use it with a screen/TV (instead of remote-control over the network), you might like that one.
https://www.raspberrypi.org/products/raspberry-pi-400/

I totally agree on the memory card, that can make a _huge_ different (usually much more important than more RAM). Something like a Sandisk Ultra (or an Extreme) is the way to go.

I always have a lot of cables and power supplies lying around so I never looked at the starter kits. But if it has a good memory card and the price is right I guess it might make sense.

**Comment by decodeais** [comment]
I have checked it. You need more than 8GB. I  tried it with 8GB. I lost a hole day.  Let me know if you find a way.  The problem is the build process for wxPython.

**Comment by MeanHat** [comment]
Hi @WouterJD - good luck with your RPi developments. Following on from the other contributions from @switchabl and @decodeais I wanted to add:
1. **RPi Zero** works fine with your FortiusANT using ANT+dongle. It is headless, drives a Tacx Fortius and is set to calibrate each time it starts. 
2. I have struggled to get a Bluetooth implementation working on an **RPI Zero**. It has an ARMv6 instruction set (unlike the current Rpi3 and RPi4) and I have struggled with the Node JS installation (see the instructions from @wtal710174 in #192) using the unofficial build for ARMv6. If anyone has any suggestions they would be welcome.
3. FortiusANT runs well on a headless **RPi3B** build using instructions from #192. @wtal710174 has a pre-built wxPython package to download that saves a lot of time building wxPython. (However, it is not suitable for an **RPi Zero** with ARMv6). It is also headless and is calibrated manually using a manual runoff test.

**Comment by WouterJD** [comment]
> have checked it. You need more than 8GB. I tried it with 8GB. I lost a hole day. Let me know if you find a way. The problem is the build process for wxPython.

Do I understand correctly that 4GB RAM and 8GB SANdisk are required?

**Comment by decodeais** [comment]
If you must recompile wxPhyton its definitly not enough.
For the precompiled version its ok. The speed of the SD-card saves a lot of time, when you are copying the image, making updates and so on.
I think its better to start with a little faster Raspi.  4GB is more than enough.
The gratest advantage of Raspi4 is the possibility of switching on ant of by using a button. Switching on and off by the power supply often caused damages on the SD-Card.

**Comment by switchabl** [comment]
There is also the possibility of building in a Docker/QEMU container on a PC. Building big packages directly on the Pi has always been an issue (in particular with the older ones/the Zero).

**Comment by WouterJD** [comment]
Meaning starting off with rpi is yet-another-world to explore🤨🤔🤪

**Comment by WouterJD** [comment]
And perhaps that's the reason to do it

**Comment by wtal710174** [comment]
@decodeais I just found this add on to the code. This is a great idea! I tried something similar but due to not being too familiar with python and github push and pull requests at this time I tried to build something without changing the main project. [FortiusAnt One Button Controller for Raspberry](https://github.com/WouterJD/FortiusANT/issues/192#issuecomment-757495938). I think it could be helpful to add some more features to display the following (This might be included already, since I did not read the code yet and just did look at the comments):

- Kick pedal for calibration
- Show connection of ANT and Bluetooth 
- Indicate the calibration of the steering if activated according to the output in the GUI or the terminal for calibrating the steering frame (see pull request [Steering](https://github.com/WouterJD/FortiusANT/pull/207) by @marcoveeneman)
- Indicate if node and ANT or bluetooth are up and running and the Raspi is ready to connect to the Cycling software (Similar to the green light I am using).
- Maybe even implement an optional button to start and stop the raspberry

I tried to use the GPIO pins in such a way that all fits into a regular 2x5 connector, maybe that is still possible.

**Comment by WouterJD** [comment]
Hi @decodeais thanks again for providing the idea, code and the docu.
I have started off with RPI; would you mind I integrate it into FortiusAnt, using five leds, not exactly following your code?

**Comment by WouterJD** [comment]
> I think it could be helpful to add some more features to display the following

Working on it:-)

**Comment by wtal710174** [comment]
> > I think it could be helpful to add some more features to display the following
> 
> Working on it:-)

Let me know if I can provide any help. I just merged the code into your project yesterday on my RPI. Starting to work on making it work with BLE and the five LED's.

**Comment by decodeais** [comment]
I was sure that my LED's were only the first step.
The implementation would be much better when we don't switch the LED's direct in your code. It would be much better when you provide status flags which can be interpreted in **one** little LED function. This should be done before the LED-switching is widespread to the hole sourcecode.
Feel free to add some LED's.

**Comment by WouterJD** [comment]
I have integrated the LEDs and a shutdown button in FortiusAnt. Do you agree to close this pull request?

**Comment by decodeais** [comment]
Of course, I'm very curious how it works. The source code looks much more professional in your stile.

**Pull request closed without merging**
