### PR TITLE
SCS+PWR profile added

### PR DESCRIPTION
**Pull request by WouterJD**
@BikeBeppe64 work in progress; Speed and Cadence Sensor is implemented.
An excercise for next step; the PWR profile

image

### CODE REVIEW

**Comment by BikeBeppe64** [comment]
Hi WouterJD,

I don't know what I have ti do with following files sent me.

Commit Summary
SCS profile added
File Changes
A StartUp/ExplorAnt.bat (3)
M StartUp/FortiusAnt (gui, autostart, simulate)==test ANT===.bat (5)
M pythoncode/ExplorAnt.py (44)
M pythoncode/FortiusAntBody.py (31)
M pythoncode/FortiusAntGui.py (5)
M pythoncode/antDongle.py (86)
A pythoncode/antSCS.py (83)
M pythoncode/usbTrainer.py (35)
Patch Links:
https://github.com/WouterJD/FortiusANT/pull/95.patch
https://github.com/WouterJD/FortiusANT/pull/95.diff


Could you help me on this ?

Anyway thanks a lot for your big help.

How to get you a beer ?

Regards
Giuseppe

**Comment by WouterJD** [comment]
Sorry @BikeBeppe64 for not explaining

Initially you downloaded FortiusANT from the so-call master-branch: the official released version.

I now created a sub-branch "#79-Add-PWR-SCS-Profile" which is the working-area to create the newer version. It only contains the python-code.

Never mind; I will add PWR-profile first, including the executable, and then we talk further. OK?

**Comment by BikeBeppe64** [comment]
Every needs from me, ask...

**Comment by WouterJD** [comment]
Va bene!

**Comment by BikeBeppe64** [comment]
Hai fatto una nuova versione di FortiusAnt (3.1.1) Devo scaricarla per provarla oppure continuare con la vecchia versione (3.0) ?

**Comment by WouterJD** [comment]
Continui con tua 3.0 
Questo versione è per risolvere un problema

PWR profilo e in corso di lavoro😜

**Comment by WouterJD** [comment]
I have implemented PWR-profile as well, so it's ready for test with your Garmind Edge.

Download the executable from:
https://github.com/WouterJD/FortiusANT/blob/%2379-Add-PWR-SCS-Profile/WindowsExecutable/FortiusANT.exe

This is version 3.2

------------------------

This executable is in the sub-branch " #79-Add-PWR-SCS-Profile". That branch will exist untill you and me are ready with test.
Then it is merged into the main branch (master) and becomes the office release.

**Comment by WouterJD** [comment]
> How to get you a beer ?

@BikeBeppe64 e cosí ci riconosciamo! Sei proprio il prio che mi lo chiede! Sarebbe bello no?
La distanza force lo faccia difficile, ma chi sa nel futuro!

**Comment by WouterJD** [comment]
@Alanimus might be of your interest since you asked for hooks on a Speed and Cadence sensor. FortiusANT now broadcasts an SCS, receiviing from is easy to implement. Just drop a note how far you are with your developments.

**Comment by BikeBeppe64** [comment]
@Wouter JD I'll get test sooner with FortiusAnt 3.2 and my Edge 800 (no FE-C channel)

**Comment by WouterJD** [comment]
Yes, that what it's built for!

**Pull request merged**
