### PR TITLE
i-Vortex implemented; ready for field-test

### PR DESCRIPTION
**Pull request by WouterJD**
i-Vortex implementation is ready and tested by myself.

Two main changes:
- headunit is now integrated
- by putting the headunit in PCmode it does no longer control the i-Vortex and hence the controlling by FortiusANT works.

@darkpotpot, @iepuzaur @tobekas @plundberg75
I am curious to hear what your experiences are!

### CODE REVIEW

**Comment by darkpotpot** [comment]
Hi,
my trainer is finally working again (it was blinking red/green for several days...). So I updated the master branch but couldn't make the HeadUnit work with FortusAnt. Pushing up arrow or down arrow didn't make any change.

The command I use is "**python.exe .\FortiusAnt.py -t i-Vortex -g -M**". Is it good ?

Also, the speed is still not good. It is 4 km/h in FortiusAnt and 22 km/h on HeadUnit. Did you experienced the same when testing with yours?

Thank you for your work.

**Comment by WouterJD** [comment]
do you use version 3.1?
Master branch version 3 does not work indeed


https://github.com/WouterJD/FortiusANT/tree/%2346-Support-Tacx-i-Vortex?files=1

**Comment by darkpotpot** [comment]
Yes I pulled the branch after seeing my mistake.
It worked perfectly with zwift !

I only have the impression that the résistance is too hard. It was 50% difficulty, and a 3% slope was already something hard.

**Comment by WouterJD** [comment]
@darkpotpot thanks for feedback!

Zwift sends a grade (and that is displayed on the screen by FortiusANT)
The grade is converted to the required power TargetPower = f(grade, speed, userweight) + some additional constants using the formula's as provided by [Gribble](https://www.gribble.org/cycling/power_v_speed.html) see [pythoncode](https://github.com/WouterJD/FortiusANT/blob/%2346-Support-Tacx-i-Vortex/pythoncode/usbTrainer.py#L621).

The TargetPower is directly passed to the iVortex.

To evaluate the resistance; you could use the -M flag and select the grade manually and check whether that is realistic. In case of doubt or questions, post the logfile (-d127) and I will check.

Success!

**Comment by WouterJD** [comment]
@darkpotpot, @iepuzaur @tobekas @plundberg75
if no further feedback received, I suppose i-Vortex is integrated and will merge into master-branch.
New issues can be raised, of course.


Thanks.

**Comment by darkpotpot** [comment]
@WouterJD Thank you for the information, I'll have a look at it when I'll have time. Indeed using the manual grade is the best way for me to test it.

Thank you for your work on this.

**Comment by WouterJD** [comment]
I merged i-vortex into the master, feedback is appreciated anyway
Succes!

**Comment by darkpotpot** [comment]
I tested the master and it worked perfectly. I did a zwift ride of almost 2 hours without any problems.

**Comment by WouterJD** [comment]
Lucky you. I did a rouvy ride yesterday and crashed on two locations (in the sofware). I will publish the solution asap. Caused by special circumstances.
Thanks for testing.

**Pull request merged**
