### PR TITLE
Fixed GUI crashes on RaspberryPi.

### PR DESCRIPTION
**Pull request by GewoonGijs**
Hi Wouter, 

I tested my fixes today with my Tacx and succesfully made my first trip on Zwift.

The mx.CallAfters() around the update of the gauges might not be absolutely necessary but for the responsiveness of the GUI buttons I think it is a huge improvement. All the other locations have the risk of being called from another than the GUI thread.

### CODE REVIEW

**Comment by GewoonGijs** [comment]
Fixed #216

**Comment by WouterJD** [comment]
Gijs, welkom!
Welcome in the FortiusANT community and thanks for studying the subject.

Before merging the request, I would like to understand what issue is being resolved.
If I understand well what I did, the only wx-calls are done from the GUI thread.

I will study your code suggestions asap; and do some other question-answering first.

**Comment by GewoonGijs** [comment]
Hi Wouter,

The problem arises because a separate Thread is started after the RunOff or Start button is pressed.

In FortiusANTGui.py this results in calling callRunOff() in a "non-gui" thread and not the main wx thread (line 1193) the same issue is with callTacx2Dongle()  (line 1233). 

This results in calling setValues() and setMessages() in GuiMessage2Main() from the "non-gui Thread", and in these functions all the updates to the GUI are executed.

It took me quite a while to find this little nasty bug.

**Comment by WouterJD** [comment]
Looking at your implementation I would prefer below code

```
    def SetValues(self, fSpeed, iRevs, iPower, iTargetMode, iTargetPower, fTargetGrade, \
                        iTacx, iHeartRate, \
                        iCrancksetIndex, iCassetteIndex, fReduction):
        wx.CallAfter(
                    self.SetValuesGUI, \
                    fSpeed, iRevs, iPower, iTargetMode, iTargetPower, fTargetGrade, \
                    iTacx, iHeartRate, \
                    iCrancksetIndex, iCassetteIndex, fReduction)

    def SetValuesGUI(self, fSpeed, iRevs, iPower, iTargetMode, iTargetPower, fTargetGrade, \
                        iTacx, iHeartRate, \
                        iCrancksetIndex, iCassetteIndex, fReduction):

```
because it allows "anybody" to call SetValues() and solve the problem once.

I was not aware that wx had to be called from the main thread only.
Therefore CallAfter is new to me (thanks for teaching this) so I'm interested in your view.

**Comment by WouterJD** [comment]
I hope this image helps.

PS. handling of Stop/Close button may have issues as well.

image

**Comment by WouterJD** [comment]
Please check https://github.com/WouterJD/FortiusANT/blob/%23216-GUI-crash-on-raspberry/pythoncode/FortiusAntGui.py

**Comment by GewoonGijs** [comment]
@Wouter, I totally agree with you, the solution you proposed is cleaner and more robust. I just tested it in simulation mode, and it runs just as smoothly as the fixes I tried before. And that makes sense.

Thanks alot, I will close the PR.

**Pull request closed without merging**
