### PR TITLE
Add support for Bushido T1981/T1982 and Genius T2021

### PR DESCRIPTION
**Pull request by switchabl**
This implements support for the Tacx Bushido brake (T1981)/head-unit (T1982) and Tacx Genius (T2021) brake (#101, #117).

PR #131 should be considered obsolete.

Bushido support should still be considered experimental.

I have not bumped the version to 5.0 since this doesn't include new .exe files for Windows. I still have problems building these locally. Also maybe a good time to remove them from the repository altogether and make a GitHub release instead?

@WouterJD Let me know if you have questions or want me to change something.

I will write up a few notes on usage and limitations later that you can help you update the manual.

When you merge this eventually, you might want to consider "Squash and merge" because this branch has a lot of commit history that maybe isn't too relevant.

### CODE REVIEW

**Comment by switchabl** [comment]
antDongle.py doesn't seem to diff properly, maybe I still have the line-endings wrong there. I will try to fix.

**Comment by tschmidty69** [comment]
@switchabl Nice!. I have a fortius but had picked up a Bushido (T1981 and T1982) a few years ago but haven't done much. It was very iffy getting it to connect to the TTS4 software. I am having issues with the head unit not turning on. DOes it require the head unit (guessing yes)?

**Comment by switchabl** [comment]
@tschmidty69 Unfortunately yes. We currently don't talk to the brake directly, but let the head unit do most of the work. The reason is that the head unit protocol is very similar to that used by the Genius, so it was a bit of a low-hanging fruit.

That being said, controlling the brake directly is technically possible and could be implemented if there is enough interest/help (newer version of TTS4 do this). Some work has been done on reverse-engineering the protocol (https://github.com/fluxoid-org/CyclismoProject/wiki/Tacx-Bushido-Brake-protocol) and I could probably figure out the rest relatively quickly. But getting it to work is another story because I don't have a Bushido and even just adapting the Genius implementation without the ability to test it myself was hard enough.

**Comment by tschmidty69** [comment]
@switchabl I was able to get the head unit working, had to open it up and solder the pads where the batter connections were. I think sweat had gotten in and corroded things. Had to actually solder some wires to get eh connection solid. I'll try test tomorrow. Should it just attach right away? Not sure how to test if the head unit is connecting to the ant stick in the first place.

**Comment by WouterJD** [comment]
> When you merge this eventually, you might want to consider "Squash and merge" because this branch has a lot of commit history that maybe isn't too relevant.

I would think if I merge this, I only get the latest version into my project; if not please educate me - I do not now what squash&merge is.

**Comment by switchabl** [comment]
> I would think if I merge this, I only get the latest version into my project; if not please educate me - I do not now what squash&merge is.

If you do a normal merge, you absorb all the all the commit history as well. E.g. you can see all the commits previously made on the Bluetooth branch in the FortiusANT history: https://github.com/WouterJD/FortiusANT/commits/master

Since this branch contains a lot of small commits, some quite irrelevant, and made a long time ago, doing a plain merge would mess up the FortiusANT history quite a bit. A squash & merge will make it appear as a single big commit in the master branch.

This is a nice description of the different merge types I think: https://cloudfour.com/thinks/squashing-your-pull-requests/

**Comment by switchabl** [comment]
@WouterJD I've collected some information on how to use this. You still have to write it up, but hopefully it will help you with updating the manual.

Genius:
- installing T19xx USB drivers is not required
- turn Genius brake on
- run FortiusANT with '-a -g -H0 -t Genius'
- pairing to the Genius is automatic (may take a minute)
- calibration is initiated automatically after pairing
- when requested, nudge the wheel forward by hand (or give the pedals a light kick)
- the brake spins up the wheel automatically, DO NOT PEDAL DURING CALIBRATION
- after calibration is complete, a calibration value will be shown
  a value between -15 and 15 is good
  a value lower than -15 indicates that the roller pressure is too low, should increase using knob on the trainer
  a value lower than +15 indicates that the roller pressure is too high, should decrease using knob on the trainer
- to re-do calibration, turn the brake off and on again, then restart FortiusANT
- for consistent results, warm up for ~5 minutes before starting FortiusANT is recommended
- calibration (and warm-up) can be skipped by adding the '-n' command-line option
  the brake remembers the last calibration value
  this should be fine if the last calibration is recent and nothing was changed/tyre pressure is the same
  FortiusANT will show 'UNCALIBRATED' to remind you the calibration is not fresh
  
known issues:
- cadence estimation by the brake is not always realiable and often seems to read 3-5rpm high
- in ERG mode the wheel sometimes takes a while to stop spinning after you stop pedaling
- downhill simulation slows down after a few seconds if you stop pedaling completely (built-in safety limitation)
- the Genius remote control (T2022) is not supported (yet)
- virtual shifting is currently not implemented for the Genius


Bushido:
- Bushido support is **experimental** (consider leaving feedback in #117)
- the Bushido head unit (T1982) is (currently) required
- head unit needs to be turned on and paired to the brake (see Tacx manual)
- calibration is done on the head unit (see Tacx manual)
- installing T19xx USB drivers is not required
- run FortiusANT with '-a -g -H0 -t Bushido'
- pairing to the Bushido is automatic (may take a minute)
- head unit buttons can be used to control FortiusANT (keymap is the same as Vortex)

known issues:
- if power is not transmitted properly, it may help to reset the head unit:
  Settings -> Info -> 10x right arrow (suggested by @TinusVee)
- virtual shifting is currently not implemented for the Bushido

@tschmidty69 Hopefully this is helpful to you too. I would suggest that you join #117 and let us know if it works. The sweat issue has always bothered me with the Tacx head units. I ended up either covering them with a towel or just putting them next to the bike because they didn't seem sweat-proof (Genius T2022 is maybe an exception). That's not really convenient of course.

**Comment by tschmidty69** [comment]
OK, had to install the windows version of python (3.9.1) and everything worked to connect, and numbers matched at a rough glance.. I couldn't do a longer test as it turns out the freewheel on my wife's bike died so I had to pair the brake by spinning the wheel by hand, lol. I sold my road bike thinking I'd get another and was riding my gravel bike until it got run over by a car in September and haven't replaced either bike since I still can't ride outside. Anyway....I think my old gravel/commuter bike will fit so I'll try to drag it up and do a longer test tomorrow, but initial tests looked good.

```
PS C:\Users\tschmidt\FortiusANT\pythoncode> py .\FortiusAnt.py -a -g -H0 -t Bushido -d 10
19:15:04,421: FortiusANT started
19:15:04,422: -a
19:15:04,423: -c False
19:15:04,423: -C 0/0
19:15:04,424: -d 10 (0b1010)
19:15:04,424: -D None
19:15:04,425: -g
19:15:04,426: -H 0
19:15:04,426: -p 1.0
19:15:04,427: -R defines Runoff: maxSpeed=40 dip=2 minSpeed=1 targetTime=7 power=100
19:15:04,428: -t Bushido
19:15:04,429: ------------------
19:15:04,986: FortiusAnt GUI started in child-process
19:15:05,295: GetDongle - Try dongle: manufacturer=Dynastream Innovations, product= ANT USBStick2, vendor= 0xfcf, product=0x1008(4104)
19:15:06,997: FortiusANT broadcasts data as an ANT+ Controlled Fitness Equipent device (FE-C), id=57591
19:15:07,188: FortiusANT receives data from an ANT+ Heart Rate Monitor (HRM display), any device
19:15:07,410: FortiusANT receives data from an ANT Tacx Bushido head unit (BHU Controller), any device
19:15:07,697: FortiusANT broadcasts data as an ANT+ Bicycle Power Sensor (PWR), id=57596
19:15:07,888: FortiusANT broadcasts data as an ANT+ Speed and Cadence Sensor (SCS), id=57595
19:15:08,096: FortiusANT receives commands from an ANT+ Generic Remote Control
```

**Pull request merged**
